version: '3.8'

services:
  backend:
#    image: patranakamo/saifa-be:v1.0.0
    build: .
    container_name: saifa-be-prod
    ports:
      - "9988:80"
    volumes:
      - .:/var/www/html #for used this volume code will update readl time but is will not check case-sensitive like linux on mac so need to be careful
      - ./lnd/data:/var/www/html/lnd/data:ro
    depends_on:
      - redis
    environment:
      APP_PASSWORD: "password"
      LN_SERVER_URL: "https://$LND_IP:$LND_REST_PORT"
      BITCOIN_NETWORK: $APP_BITCOIN_NETWORK
      REDIS_HOST: redis

  frontend:
    image: patranakamo/saifa-fe:v1.0.0
#    build:
#      context: ./../saifa-fe
#      dockerfile: Dockerfile
    container_name: saifa-fe-prod
    ports:
      - "9989:80"
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis_for_saifa_project
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
